### PR TITLE
Make pipeline compatible with features input #51

### LINKED ISSUE #51: Make pipeline compatible with features input

### PR DESCRIPTION
**Pull request by sofiaele**
This branch is responsible about making pipeline work for feature inputs (instead of audio input files). 

To test the changes together with the publicly available data, follow the below instructions: 

1. `git clone https://github.com/sofiaele/PuSQ.git`
2. Unzip the file: features_data.zip 
3. Put the contents of the repo (annotations_database.txt, dataset_parser.py, features_data) into the folder 'annotation_agreement' of the current repo. (Replace files if needed). 
4. `python3 aggregate_annotations.py -c 1 -a 3 -t 1 -g 1 -mh 4.0 -ml 2.0 -ea annotator8` 
to aggregate annotations for class 1 (expressive), minimum number of annotators = 3, type of aggregation = averaging, gender = female, low mean threshold = 2.0, high mean threshold = 4.0, exclude annotator8 (because of his high average disagreement for the specific task)
5. `python3 dataset_parser.py -n expressive_female -aa aggregated_Class1female.csv -i features_data`, to parse the data into class folders 
6. `python3 models/train_recording_level_classifier.py -i annotation_agreement/datasets/expressive_female/ -mn test_model -f` to train recording-level classifier with the previous parsed data (note: the specs of this classifier are defined in the 'models/config.yaml'. You can keep them as they are. 
7. `python3 models/test_recording_level.py -i annotation_agreement/datasets/expressive_female/negative/1_speaker27_female_MetaAudio.npz -m models/output_models/recording_level/test_model_MA.pt -m2 models/output_models/recording_level/test_model_LLA.pt`, to test input 1_speaker27_female (predict class).

### CODE REVIEW

**Comment by pakoromilas** [comment]
@sofiaele Getting the following error

python3 aggregate_annotations.py -c 1 -a 3 -t 1 -g 1 -mh 4.0 -ml 2.0 -ea annotator8
Traceback (most recent call last):
  File "aggregate_annotations.py", line 433, in <module>
    report_annotations('annotations_database_new.txt',args.class_number,args.annotators,args.type_of_aggregation,args.gender,args.mean_low,args.mean_high,args.deviation,args.exclude_annotator)
  File "aggregate_annotations.py", line 138, in report_annotations
    data = pd.read_csv(file)
  File "/home/lorki/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lorki/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/lorki/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/lorki/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lorki/anaconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'annotations_database_new.txt' does not exist: b'annotations_database_new.txt'

**Comment by pakoromilas** [comment]
fixed now.

At step 6 I'm facing the following joblib error:

joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}

Of course, this is due to the memory limitations of my PC. But maybe there is an extreme parallelization in the Gridsearch process that forces this error. @sofiaele what do you think?

**Review by pakoromilas — COMMENTED** [review]
It works as expected for me. Maybe it's a good idea to include this PR's description to the README file in order to be easier to reproduce the paper's results.

**Comment by sofiaele** [comment]
> It works as expected for me. Maybe it's a good idea to include this PR's description to the README file in order to be easier to reproduce the paper's results.

Do you think it s better to include it to a readme file in PuSQ repo?

**Comment by pakoromilas** [comment]
Yes, I think that the PuSQ repo should be connected with readys and contain a guide to reproduce the expiriments. However, we can discuss the chance of including a demo in the readys repo using the PuSQ data. 

For the time being let's leave it as is

**Pull request merged**
